// <auto-generated />
namespace CorpersWelfareManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CreateComponent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateComponent));
        
        string IMigrationMetadata.Id
        {
            get { return "201607251914108_CreateComponent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
